#
init:
	surrealgo_migrate init

# used to create new migrations 
migrations-new:
	surrealgo_migrate migrations new add_users

# used to run applications up
migrations-up:
	surrealgo_migrate migrations up
