#
init:
	surrealgo_migrate init

# used to create new migrations 
migrations-new:
	surrealgo_migrate migrations new add_users

# used to run applications up migrates the latest files by checking the timestamp
migrations-up:
	surrealgo_migrate migrations up

# migrate down added
migrations-down:
	surrealgo_migrate migrations down